name: Run foundry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.0.6
        with:
          version: 1.0.6
      - name: Run build
        run: forge build

      - name: Run tests
        run: forge test -vvv

      - name: Run snapshot
        run: forge snapshot
